Repository astronomy-club-at-nitic/quiz-rally, pull requests merged in 2023-08, with the labels that each got.

#22 `/[questionId]/` ページを実装
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/[questionId]/layout.tsx
  src/app/[questionId]/page.tsx
  src/app/layout.tsx
  src/asset/map/1.png
  src/asset/map/2.png
  src/asset/map/3.png
  src/component/common/dialog.tsx
  src/component/layout/blessing-modal.tsx
  src/component/layout/question-header.tsx
  src/component/question/access-map-section.tsx
  src/component/question/answer-explanation-section.tsx
  src/component/question/answer-status.tsx
  src/component/question/attention.tsx
  src/component/question/choice-card.tsx
  src/component/question/question-form-section.tsx
  src/component/question/question-page.tsx
  src/constant/question.ts
  src/icon/arrow-left-icon.tsx
  src/icon/check-icon.tsx
  src/icon/confetti-ball-icon.tsx
  src/icon/cross-icon.tsx
  src/icon/gift-icon.tsx
  src/icon/map-pin-icon.tsx
  src/icon/party-popper-icon.tsx
  src/icon/qr-code-icon.tsx
Labels: 🍱 asset, 📦️ build, 🔧 config, ✨ feature

#61 各問題の `Question["hashedToken"]` の値を修正
  src/constant/question.ts
Labels: 🖋️ typography

#63 型`StaticImageData`をパッケージ`next/image`から読み込むようにした。
  src/type/static-image-data.ts
Labels: ♻ refactor

#68 質問カード`<QuestionCard>`と解答状況アイコン`<AnswerStatusIcon>`を追加した。
  next.config.js
  src/app/page.tsx
  src/component/question/question-page.tsx
  src/component/questions/answer-status-icon.tsx
  src/component/questions/question-card.tsx
  src/constant/question.ts
Labels: ✨ feature

#69 フッター`<Footer>`を実装した。
  src/app/layout.tsx
  src/asset/astro-club-logo.png
  src/asset/icon.png
  src/component/layout/footer.tsx
Labels: ✨ feature
